"""Train the proxy reward model: BCE correctness classifier on RM-pool rollouts.

Trained on a deliberately limited subset of the pool (~2-4k rollouts). That
limitation os the only intended source of RM imperfection - the exploitable
surface the policy is meant to find at RL time. Distribution shift would be an
unintended second source, so train and eval rollouts both come from the same 
pool, generated by the same checkpoint the policy starts from.

The split is by question, not by rollout: the pool holds G=8 rollouts per
question, so a random rollout split would leave siblings of an eval question in
train and inflate held-out accuracy.

Target: held-out accuracy ~70-80%. Read it against majority baseline
(~0.67 at pos_rate 0.327), which every eval prints alongside it.
"""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

import argparse
import json
import math
import random

import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score

from rm import RM_MODEL, load_rm, score

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--pool", default="data/rm_pool.jsonl")
    p.add_argument("--model", default=RM_MODEL)
    p.add_argument("--train_questions", type=int, default=400) # 400 x G=8 -> 3200 rollouts
    p.add_argument("--eval_questions", type=int, default=400)
    p.add_argument("--epochs", type=int, default=2)
    p.add_argument("--batch_size", type=int, default=8)
    p.add_argument("--eval_batch_size", type=int, default=16)
    p.add_argument("--lr", type=float, default=1e-5)
    p.add_argument("--weight_decay", type=float, default=0.0)
    p.add_argument("--warmup_ratio", type=float, default=0.1)
    p.add_argument("--max_grad_norm", type=float, default=1.0)
    p.add_argument("--max_length", type=int, default=768)
    p.add_argument("--pos_weight", type=float, default=None)
    p.add_argument("--dtype", default="bfloat16", choices=["bfloat16","float32"])
    p.add_argument("--out_dir", default="results/rm_v1")
    p.add_argument("--seed", type=int, default=0)

    return p.parse_args()

def load_pool(path:str) -> list[dict]:
    with open(path) as f:
        return [json.loads(line) for line in f]

def split_by_question(rows, n_train_q, n_eval_q, seed):
    """Disjoint question sets - a question's 8 rollout never straddle the split."""
    questions = list(dict.fromkeys(r["question"] for r in rows))
    random.Random(seed).shuffle(questions)
    eval_qs = set(questions[:n_eval_q])
    train_qs = set(questions[n_eval_q:n_eval_q + n_train_q])
    train = [r for r in rows if r["question"] in train_qs]
    held = [r for r in rows if r["question"] in eval_qs]
    return train, held

def evaluate(model, tokenizer, rows, device, batch_size, max_length) -> dict:
    """Held-out metrics, scored through rm.score - the exact path RL time uses."""
    logits = score(model, tokenizer, [r["text"] for r in rows], device, 
                   batch_size=batch_size, max_length=max_length)

    labels = torch.Tensor([float(r["correct"] for r in rows)])
    pred = (logits > 0).float()
    pos, neg = labels == 1, labels == 0

    tpr = pred[pos].mean().item()
    tnr = (1.0 - pred[neg]).mean().item(0)
    pos_rate = labels.mean().item()

    return {
        "acc":(pred==labels).float().mean().item(),
        "majority_baseline": max(pos_rate, 1-pos_rate), # what "do nothing" scores
        "auroc": float(roc_auc_score(labels.numpy(), logits.numpy())),
        "balanced_acc": 0.5 * (tpr+tnr),
        "tpr": tpr,
        "tnr": tnr,
        "pos_rate":pos_rate,
        "mean_logit_pos": logits[pos].mean().item(),
        "mean_logit_neg": logits[neg].mean().item(),
    }

def main():
    args = parse_args()
    torch.manual_seed(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    os.makedirs(args.out_dir, exist_ok=True)

    rows = load_pool(args.pool)
    train_rows, eval_rows = split_by_question(
        rows, args.train_questions, args.eval_questions, args.seed
    )

    train_pos = sum(r["correct"] for r in train_rows) / len(train_rows)
    print(f"pool={len(rows)} train={len(train_rows)} eval={len(eval_rows)}"
          f"train_pos_rate={train_pos:.3f}", flush=True)

    model, tokenizer = load_rm(args.model, dtype=getattr(torch,args.dtype))
    model.to(device)

    optim = torch.optim.AdamW(model.parameters(), lr=args.lr,
                              weight_decay=args.weight_decay)
    steps_per_epoch = math.ceil(len(train_rows)/ args.batch_size)
    total_steps = steps_per_epoch * args.epochs
    warmup = max(int(args.warmup_ratio * total_steps), 1)

    def lr_lambda(step):
        if step < warmup:
            return (step+1) / warmup
        return max(0.0, 1.0 -(step -warmup) / max(total_steps-warmup, 1))

    sched = torch.optim.lr_scheduler.LambdaLR(optim, lr_lambda)
    pos_weight = (torch.tensor(args.pos_weight, device= device)) if args.pos_weight is not None else None

    idx = list(range(len(train_rows)))
    rng = random.Random(args.seed)
    history = []

    for epoch in range(args.epochs):
        model.train()
        rng.shuffle(idx)
        running = 0.0

        for step, start in enumerate(range(0,len(idx), args.batch_size)):
            batch = [train_rows[j] for j in idx[start:start+args.batch_size]]
            enc = tokenizer(
                [r["text"] for r in batch], return_tensors="pt", padding=True,
                truncation=True, max_length=args.max_length
            ).to(device)
            labels = torch.tensor([float(r["correct"]) for r in batch], device=device)

            logits = model(**enc).logits.squeeze(-1).float()
            loss = F.binary_cross_entropy_with_logits(logits, labels, pos_weight=pos_weight)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.max_grad_norm)
            optim.step()
            sched.step()
            optim.zero_grad(set_to_none=True)

            running += loss.item()
            if step % 20 == 0:
                print(f"epoch {epoch} step {step}/{steps_per_epoch}"
                      f"loss={running/ (step+1):.4f}", flush=True)

        metrics = evaluate(model, tokenizer, eval_rows, device,
                           args.batch_size, args.max_length)
        metrics["epoch"] = epoch
        metrics["train_loss"] = running/steps_per_epoch
        history.append(metrics)
        print(json.dumps(metrics, indent=2), flush=True)


    rm_dir = os.path.join(args.out_dir, "rm")
    model.save_pretrained(rm_dir)
    tokenizer.save_pretrained(rm_dir)
    with open(os.path.join(args.out_dir, "metrics.json"),"w") as f:
        json.dump({"args":vars(args), "history":history}, f, indent=2)

    print(f"saved RM to {rm_dir}, metrics to {args.out_dir}/metrics.json")


if __name__ == "__main__":
    main()